services:
  web:
    build: ./web
    restart: unless-stopped
    init: true
    ports:
      - 3000:3000
  bot:
    build: ./bot
    restart: unless-stopped
    init: true
    ports:
      - 1337:1337
    environment:
      - FLAG=SECCON{sts2_wi11_steal_my_time_ag4in}
